name: Hello world
on: workflow_dispatch
jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build step
      run: echo "Welcome sounabh"
  test:
     runs-on: ubuntu-latest
     steps:
      - name : Test step
        run : echo "Test the code"
  deploy:
      runs-on: ubuntu-latest
      steps:
      - name: Deploy step
        run : echo "Deploy the code"

        

        

        
