# name: Hello world

# on:
#   push:
#     branches:
#       - main
#       - feature/pr

#   pull_request:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Build step
#         run: echo "Welcome ${{vars.MY_NAME}}"

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build

#     steps:
#       - name: deploy step
#         run: echo "Welcome deploy step check again"